/**
* JIKAN REST Server API
* Mobil labor API leírás.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Genre
import io.swagger.client.models.Producer

/**
 * 
 * @param request_hash 
 * @param request_cached 
 * @param request_cache_expire 
 * @param mal_id 
 * @param url 
 * @param image_url 
 * @param trailer_url 
 * @param title 
 * @param title_japanese 
 * @param type 
 * @param source 
 * @param episodes 
 * @param status 
 * @param airing 
 * @param aired 
 * @param duration 
 * @param rating 
 * @param score 
 * @param rank 
 * @param popularity 
 * @param memebers 
 * @param synopsis 
 * @param premiered 
 * @param broadcast 
 * @param producers 
 * @param genres 
 * @param opening_themes 
 * @param ending_themes 
 */
data class AnimeDetails (
    val request_hash: kotlin.String? = null,
    val request_cached: kotlin.Boolean? = null,
    val request_cache_expire: kotlin.Int? = null,
    val mal_id: kotlin.Int? = null,
    val url: kotlin.String? = null,
    val image_url: kotlin.String? = null,
    val trailer_url: kotlin.String? = null,
    val title: kotlin.String? = null,
    val title_japanese: kotlin.String? = null,
    val type: kotlin.String? = null,
    val source: kotlin.String? = null,
    val episodes: kotlin.Int? = null,
    val status: kotlin.String? = null,
    val airing: kotlin.Boolean? = null,
    val aired: kotlin.Any? = null,
    val duration: kotlin.String? = null,
    val rating: kotlin.String? = null,
    val score: kotlin.Double? = null,
    val rank: kotlin.Int? = null,
    val popularity: kotlin.Int? = null,
    val memebers: kotlin.Int? = null,
    val synopsis: kotlin.String? = null,
    val premiered: kotlin.String? = null,
    val broadcast: kotlin.String? = null,
    val producers: kotlin.Array<Producer>? = null,
    val genres: kotlin.Array<Genre>? = null,
    val opening_themes: kotlin.Array<kotlin.String>? = null,
    val ending_themes: kotlin.Array<kotlin.String>? = null
) {

}

