/**
* JIKAN REST Server API
* Mobil labor API leírás.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Anime

/**
 * 
 * @param request_hash 
 * @param request_cached 
 * @param request_cache_expiry 
 * @param monday 
 * @param tuesday 
 * @param wednesday 
 * @param thursday 
 * @param friday 
 * @param saturday 
 * @param sunday 
 */
data class AnimeList (
    val request_hash: kotlin.String? = null,
    val request_cached: kotlin.Boolean? = null,
    val request_cache_expiry: kotlin.String? = null,
    val monday: kotlin.Array<Anime>? = null,
    val tuesday: kotlin.Array<Anime>? = null,
    val wednesday: kotlin.Array<Anime>? = null,
    val thursday: kotlin.Array<Anime>? = null,
    val friday: kotlin.Array<Anime>? = null,
    val saturday: kotlin.Array<Anime>? = null,
    val sunday: kotlin.Array<Anime>? = null
) {

}

