/**
* JIKAN REST Server API
* Mobil labor API leírás.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.Genre
import io.swagger.client.models.Producer

/**
 * 
 * @param mal_id 
 * @param url 
 * @param title 
 * @param imgage-url 
 * @param synopsis 
 * @param type 
 * @param airing_start 
 * @param episodes 
 * @param members 
 * @param genres 
 * @param source 
 * @param producers 
 * @param score 
 * @param licensors 
 * @param r18 
 * @param kids 
 * @param continuing 
 */
data class Anime (
    val mal_id: kotlin.Int? = null,
    val url: kotlin.String? = null,
    val title: kotlin.String? = null,
    val imgage_url: kotlin.String? = null,
    val synopsis: kotlin.String? = null,
    val type: kotlin.String? = null,
    val airing_start: kotlin.String? = null,
    val episodes: kotlin.Int? = null,
    val members: kotlin.Int? = null,
    val genres: kotlin.Array<Genre>? = null,
    val source: kotlin.String? = null,
    val producers: kotlin.Array<Producer>? = null,
    val score: kotlin.Double? = null,
    val licensors: kotlin.Array<kotlin.String>? = null,
    val r18: kotlin.Boolean? = null,
    val kids: kotlin.Boolean? = null,
    val continuing: kotlin.Boolean? = null
) {

}

