/**
* JIKAN REST Server API
* Mobil labor API leírás.
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param mal_id 
 * @param type 
 * @param name 
 * @param url 
 */
data class Producer (
    val mal_id: kotlin.Int? = null,
    val type: kotlin.String? = null,
    val name: kotlin.String? = null,
    val url: kotlin.String? = null
) {

}

